[workspace]
resolver = "3"
members = [".", "crates/*"]
default-members = [".", "crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
readme = "README.md"
documentation = "https://www.docs.rs/onyx"
homepage = "https://www.github.com/aacebo/onyx"
repository = "https://www.github.com/aacebo/onyx"

[package]
name = "onyxrs"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "onyx"
doctest = false

[features]
default = []
ort = ["dep:onyx-ort"]

[dependencies]
onyx-core = { path = "crates/onyx-core" }
onyx-ort = { path = "crates/onyx-ort", optional = true }
