[package]
name = "onyx-ort"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
ort = { version = "2.0.0-rc.12" }
hf-hub = { version = "0.5" }
tracing = { version = "0.1" }
tokenizers = { version = "0.23", features = ["http"] }

onyx-core = { path = "../onyx-core" }
