[package]
name = "onyx-core"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[features]
default = []

[dependencies]
serde = { version = "1", features = ["derive", "rc"] }
url = { version = "2", features = ["serde"] }

[dev-dependencies]
serde_json = "1"
