[package]
name = "onyx-core"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
serde = { version = "1", features = ["derive", "rc"] }
async-trait = "0.1"
ndarray = { version = "0.17", features = ["serde"] }

