[package]
name = "onyx-tokio"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[features]
default = []
http = ["reqwest", "onyx-core/http"]

[dependencies]
onyx-core = { path = "../onyx-core" }
tokio = { version = "1.52", features = ["fs"] }
reqwest = { version = "0.13", optional = true }
