[package]
name = "onyx-huggingface"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[dependencies]
candle-core = "0.10.2"
tokenizers = { version = "0.23", features = ["http"] }
tracing = { version = "0.1" }

onyx-core = { path = "../onyx-core" }
