[package]
name = "onyx-candle"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
doctest = false

[features]
default = []
http = ["onyx-core/http"]
json = ["onyx-core/json", "serde_json"]

[dependencies]
onyx-core = { path = "../onyx-core" }
candle-core = { version = "0.10" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }

[dev-dependencies]
serde_json = "1"
